spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/note?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Hong_Kong&allowPublicKeyRetrieval=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 180000
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath*:mappers/*.xml
logging:
  level:
    org.springframework: WARN
    io.github.hingbong.cloudnote.mapper.NotebookMapper: DEBUG
    io.github.hingbong.cloudnote.mapper.UserMapper: DEBUG
    io.github.hingbong.cloudnote.mapper.NoteMapper: DEBUG